webtalk_init -webtalk_dir C:/Users/travi/Desktop/FPGA_Research/Code/RedPitaya-master/fpga/prj/v0.94/project/redpitaya.sim/sim_1/behav/xsim/xsim.dir/red_pitaya_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 30 22:41:52 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5c5ab265-a489-46a5-9bd9-00a23a550dd4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "609356f1b9f14684b661b8913bb3ad88" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "196" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1000007500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "7" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "54.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "4208328_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4074412143 -regid "" -xml C:/Users/travi/Desktop/FPGA_Research/Code/RedPitaya-master/fpga/prj/v0.94/project/redpitaya.sim/sim_1/behav/xsim/xsim.dir/red_pitaya_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/travi/Desktop/FPGA_Research/Code/RedPitaya-master/fpga/prj/v0.94/project/redpitaya.sim/sim_1/behav/xsim/xsim.dir/red_pitaya_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/travi/Desktop/FPGA_Research/Code/RedPitaya-master/fpga/prj/v0.94/project/redpitaya.sim/sim_1/behav/xsim/xsim.dir/red_pitaya_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
